from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Union

from genesis.modules.citations.agent import CitationsAgent


class PaperSynthesizer:
    def __init__(self, project_root: Union[str, Path]):
        self.project_root = Path(project_root)

    def synthesize(self, project_id: str) -> dict[str, str]:
        project_dir = self.project_root / project_id
        paper_dir = project_dir / "outputs" / "paper"
        paper_dir.mkdir(parents=True, exist_ok=True)
        references = paper_dir / "references.bib"
        citations = CitationsAgent(references)
        bibtex = citations.format_bibtex({"title": "Genesis v1", "year": 2026})
        references.write_text(bibtex, encoding="utf-8")

        template = (Path(__file__).parent / "templates" / "main.tex").read_text(encoding="utf-8")
        tex = template.replace("{{TITLE}}", f"Genesis results for {project_id}")
        tex = tex.replace("{{ABSTRACT}}", "Automated draft generated by Genesis v1.")
        tex = tex.replace("{{BODY}}", "This draft summarizes the verified project outputs.")
        tex_path = paper_dir / "main.tex"
        tex_path.write_text(tex, encoding="utf-8")
        pdf_path = paper_dir / "main.pdf"
        if subprocess.run(["which", "pdflatex"], capture_output=True, text=True).returncode == 0:
            subprocess.run(
                ["pdflatex", "-interaction=nonstopmode", tex_path.name],
                cwd=paper_dir,
                capture_output=True,
                text=True,
                check=False,
            )
        else:
            pdf_path.write_text("pdflatex unavailable; placeholder artifact", encoding="utf-8")
        return {"pdf_path": str(pdf_path), "latex_path": str(tex_path)}
